# Generated by Django 4.2 on 2023-04-29 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configurations',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('config_name', models.CharField(max_length=250)),
                ('dept_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=250)),
                ('sftp_login', models.CharField(max_length=250)),
                ('sftp_password', models.CharField(max_length=250)),
                ('carrier_name', models.CharField(max_length=250)),
                ('website_url', models.CharField(max_length=1000)),
                ('template', models.FileField(upload_to='files/')),
                ('is_scheduled', models.BooleanField(default=False)),
                ('sftp_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationEmployers',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emp_name', models.CharField(max_length=250)),
                ('emp_password', models.CharField(max_length=250)),
                ('emp_type', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('superadmin_id', models.AutoField(primary_key=True, serialize=False)),
                ('superadmin_email', models.EmailField(max_length=254, unique=True)),
                ('superadmin_name', models.CharField(max_length=250)),
                ('superadmin_password', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_name', models.CharField(max_length=250, unique=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('time', models.TimeField()),
                ('days_of_week', models.CharField(blank=True, max_length=50, null=True)),
                ('day_of_month', models.DateField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_sakon.configurations')),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_sakon.organizationemployers')),
            ],
        ),
        migrations.AddField(
            model_name='organizationemployers',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_sakon.organizations'),
        ),
        migrations.CreateModel(
            name='FileMetaData',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=250, unique=True)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=250)),
                ('carrier_name', models.CharField(max_length=250)),
                ('sftp_location_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('file_by_empid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_sakon.organizationemployers')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=250)),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_sakon.organizations')),
            ],
            options={
                'unique_together': {('dept_name', 'org_id')},
            },
        ),
        migrations.AddField(
            model_name='configurations',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_sakon.organizationemployers'),
        ),
        migrations.CreateModel(
            name='EmpDept',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_sakon.departments')),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_sakon.organizationemployers')),
            ],
            options={
                'unique_together': {('dept_id', 'emp_id')},
            },
        ),
        migrations.CreateModel(
            name='AdminOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_sakon.organizationemployers')),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_sakon.organizations')),
            ],
            options={
                'unique_together': {('admin_id', 'org_id')},
            },
        ),
    ]
