# Generated by Django 4.2 on 2023-06-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend_sakon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="employee_count",
            field=models.IntegerField(null=True),
        ),
    ]
