# Generated by Django 4.2 on 2023-05-19 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend_sakon", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="configuration_ids",
            new_name="configurations",
        ),
    ]
