# Generated by Django 4.1.7 on 2023-05-18 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend_sakon", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="emp",
            new_name="emp_id",
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="frequency",
            new_name="interval",
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="day_of_month",
            new_name="monthDay",
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="name",
            new_name="schedularName",
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="timezone",
            new_name="timeZone",
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="days_of_week",
            new_name="weekDay",
        ),
    ]
