# Generated by Django 4.1.7 on 2023-05-11 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_sakon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='filemetadata',
            old_name='sftp_location_path',
            new_name='sftp_path',
        ),
        migrations.RemoveField(
            model_name='filemetadata',
            name='file_by_empid',
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_sakon.employee'),
        ),
        migrations.AlterField(
            model_name='adminorganization',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_sakon.employee'),
        ),
        migrations.AlterField(
            model_name='adminorganization',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_sakon.organization'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_sakon.employee'),
        ),
        migrations.AlterField(
            model_name='department',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_sakon.organization'),
        ),
        migrations.AlterField(
            model_name='empdept',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_sakon.department'),
        ),
        migrations.AlterField(
            model_name='empdept',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_sakon.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_sakon.organization'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_sakon.configuration'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_sakon.employee'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='frequency',
            field=models.CharField(choices=[('1', 'Daily'), ('2', 'Weekly'), ('3', 'Monthly')], max_length=10),
        ),
    ]
