# Generated by Django 4.2 on 2023-07-05 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_sakon', '0002_alter_department_employee_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_sakon.organization'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_sakon.employee'),
        ),
    ]
