# Generated by Django 4.1.7 on 2023-05-18 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend_sakon", "0002_rename_emp_schedule_emp_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="config",
            new_name="configuration",
        ),
    ]
