# Generated by Django 4.2 on 2023-05-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend_sakon", "0002_rename_configuration_ids_schedule_configurations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="schedularName",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
