# Generated by Django 4.2 on 2023-07-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_sakon', '0003_configuration_org_jobs_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='service_providers',
            field=models.JSONField(null=True),
        ),
    ]
