# Generated by Django 4.2 on 2023-05-22 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend_sakon", "0003_alter_schedule_schedularname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="configuration",
            old_name="schedule_id",
            new_name="schedule",
        ),
    ]
