# Generated by Django 4.1.7 on 2023-05-18 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend_sakon", "0003_rename_config_schedule_configuration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="emp_id",
            new_name="emp",
        ),
    ]
