# Generated by Django 4.2 on 2023-05-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend_sakon", "0004_rename_emp_id_schedule_emp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="interval",
            field=models.CharField(
                choices=[
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="weekDay",
            field=models.CharField(max_length=250),
        ),
    ]
