# Generated by Django 4.2 on 2023-05-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend_sakon", "0004_rename_schedule_id_configuration_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="weekDay",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
