# Generated by Django 4.2 on 2023-05-30 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend_sakon", "0006_rename_time_schedule_timeduration_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="adminorganization",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="adminorganization",
            name="admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend_sakon.employee",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="interval",
            field=models.CharField(
                choices=[(1, "DAILY"), (2, "WEEKLY"), (3, "MONTHLY")], max_length=10
            ),
        ),
    ]
